web/MLV/MLV/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('viterbi_demo.urls')),
]

web/MLV/viterbi_demo/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^ajax$', views.ajax, name='ajax'),
]

web/MLV/viterbi_demo/models.py
from django.db import models


class Text(models.Model):
    content = models.TextField()
    title = models.CharField(max_length=200)

    def __str__(self):
        return self.title

web/MLV/viterbi_demo/forms.py
from django import forms
from .models import Text

PHRASE_MY_CHOICE = "Use my own text"


class InputForm(forms.Form):
    titles = list(Text.objects.values_list('title'))
    titles = [(item[0], item[0]) for item in titles] + [(PHRASE_MY_CHOICE, PHRASE_MY_CHOICE)]
    source = forms.ChoiceField(
        choices=titles,
        initial=titles[0][0],
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    user_text = forms.CharField(widget=forms.Textarea(attrs={'rows': 10, 'cols': 80, 'style': 'resize: none',
                                                             'class': 'form-control'}),
                                label="Input your own text",
                                required=False)
    sentence = forms.CharField(label="Start with (type a word or a phrase)",
                               widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    length = forms.IntegerField(min_value=1, max_value=200,
                                widget=forms.NumberInput(attrs={'class': 'form-control'})
    )

    def __init__(self, *args, **kwargs):
        super(InputForm, self).__init__(*args, **kwargs)

        if self.data and self.data.get('source') == PHRASE_MY_CHOICE:
            self.fields.get('user_text').required = True

web/MLV/viterbi_demo/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import loader
from django.core.urlresolvers import reverse
from django.contrib import messages



import my_little_viterbi
from .forms import InputForm, PHRASE_MY_CHOICE
from .models import Text


def index(request):
    if request.method == 'POST':
        form = InputForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['source'] == PHRASE_MY_CHOICE:
                raw_text = form.cleaned_data['user_text']
            else:
                t = Text.objects.get(title__exact=form.cleaned_data['source'])
                raw_text = t.content
                form.cleaned_data['user_text'] = ""
            output = my_little_viterbi.start(
                raw_text=raw_text,
                user_sentence=form.cleaned_data['sentence'],
                length=form.cleaned_data['length'],
                is_debug=False)
            messages.add_message(request, messages.INFO, output)
            return HttpResponseRedirect(reverse('index'))
    else:
        form = InputForm()
    return render(request, 'viterbi_demo/index.html', {'form': form})



def ajax(request):
    if request.is_ajax():
        form = InputForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['source'] == PHRASE_MY_CHOICE:
                raw_text = form.cleaned_data['user_text']
            else:
                t = Text.objects.get(title__exact=form.cleaned_data['source'])
                raw_text = t.content
                form.cleaned_data['user_text'] = ""
            output = my_little_viterbi.start(
                raw_text=raw_text,
                user_sentence=form.cleaned_data['sentence'],
                length=form.cleaned_data['length'],
                is_debug=False)
            return JsonResponse({"data": output})
    else:
        form = InputForm()
    return render(request, 'viterbi_demo/index_ajax.html', {'form': form})

web/MLV/viterbi_demo/templates/viterbi_demo/header.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Viterbi Demo</title>
        {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.js"></script>
</head>

web/MLV/viterbi_demo/templates/viterbi_demo/index.html
{% include "viterbi_demo/header.html"%}

<body>
<script type="text/javascript">
var myOwn = "Use my own text"
    $(document).ready(function() {
        if ($("#id_source").val() != myOwn)
        {
            $("#id_user_text").hide();
            $("label[for='id_user_text']").hide();
        }


        $("#id_source").change(function() {
            if ($("#id_source").val() == myOwn) {
                $("#id_user_text").show();
                $("label[for='id_user_text']").show();
                }
            else { $("#id_user_text").hide(); $("label[for='id_user_text']").hide();}

        });

        $("#submit_form").click(function(event) {
            if ($("#id_source").val() == myOwn || $("#id_user_text").val()) {
                if ($("#id_user_text") == undefined || $("#id_user_text").val().length < 100) {
                    $("#output").text("Please input your own text or select a different source option! The recommended text length is no less than a page.");
                    event.preventDefault();
                }
            }
        });
    });

</script>


<div class="container">
    <div class="jumbotron" style="padding-top:2em">
        <h1>Viterbi Algorithm Demo</h1>
        <h2>Simply fill out the form below</h2>
    </div>
    <div class="row">
    <div class="col-md-4 col-md-offset-4">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        <form action="{% url 'index' %}" method="post" class="form-horizontal">
            {% csrf_token %}
            {{ form.as_p }}
            <input id="submit_form" type="submit" value="Submit" class="btn btn-primary form-control"/>
        </form>


    </div></div>

    {% if messages %}
    <div class="row"  style="padding:1em">
        <div id="output" class="well">
            <p><strong>Output:</strong></p>
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}

        </div>
    </div>
    {% endif %}
    <p><a href="{% url 'ajax' %}">Try the same form in AJAX!</a></p>


</div>
</body>
</html>

web/MLV/viterbi_demo/templates/viterbi_demo/index_ajax.html
{% include "viterbi_demo/header.html"%}
<body>
<script type="text/javascript">
var myOwn = "Use my own text"

    // Cookie code below is utilized for accessing csrf cookie for AJAX
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $(document).ready(function() {
        // fixing csrf cookie check for ajax
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
        $("#output").hide();

        if ($("#id_source").val() != myOwn)
        {
            $("#id_user_text").hide();
            $("label[for='id_user_text']").hide();
        }


        $("#id_source").change(function() {
            if ($("#id_source").val() == myOwn) {
                $("#id_user_text").show();
                $("label[for='id_user_text']").show();
                }
            else { $("#id_user_text").hide(); $("label[for='id_user_text']").hide();}

        });

        $("#submit_form").click(function(event) {
            event.preventDefault();
            if ($("#id_source").val() == myOwn || $("#id_user_text").val()) {
                if ($("#id_user_text") == undefined || $("#id_user_text").val().length < 100) {
                    $("#output").text("Please input your own text or select a different source option! The recommended text length is no less than a page.");
                }
            }
            else {
                $.ajax({
                    type: "POST",
                    data: $('#input_form').serialize(),
                    success: function(result){
                        $("#output").show();
                        $("#message").text(result["data"]);
                    }
                })
            }
        });
    });

</script>

<div class="container">
    <div class="jumbotron" style="padding-top:2em">
        <h1>Viterbi Algorithm Demo            </h1>
        <h2 style="clear:both">Simply fill out the form below
            <span class="label label-success" >Now with AJAX!</span>
        </h2>

    </div>
    <div class="row">
    <div class="col-md-4 col-md-offset-4">


        <form action="" method="post" class="form-horizontal" id="input_form">
            {% csrf_token %}
            {{ form.as_p }}
            <input id="submit_form" type="submit" value="Submit"  class="btn btn-primary form-control"/>
        </form>


    </div>
    </div>
    <div class="row" style="padding:1em">
                <div id="output" class="well">
            <p><strong>Output:</strong></p>
                <p id="message">{{ message }}</p>
        </div>
    </div>
</div>
</body>
</html>

web/MLV/viterbi_demo/templates/viterbi_demo/result.html
{{ output }}